- data/io.github.mrvladus.List.desktop
This will enable the app to appear on the default home screen without needing to toggle the All Apps view.
Code taken from Flatseal: https://github.com/tchx84/Flatseal/blob/master/data/com.github.tchx84.Flatseal.desktop.in#L12C1-L13
Fixes: #24
> Add mobile metadata to .desktop file

- data/io.github.mrvladus.List.metainfo.xml
GNOME automatically excludes release descriptions on Damned Lies (GNOME Translation Platform). It's a good practice to follow the GNOME way.
This can streamline the translation process, allowing translators to focus their efforts on more critical and user-facing aspects of the application.
> data: Mark release descriptions as untranslatable

- data/io.github.mrvladus.List.metainfo.xml.in.in
These URLs are visible on Flathub and GNOME Control Center.
More information: https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-url
> Appdata related patch

- data/io.github.mrvladus.List.metainfo.xml.in.in
This metadata is invalid: custom data is a dictionary and using the same key multiple times in a dictionary does not work.
More information: https://github.com/ximion/appstream/issues/476
> appdata: Remove Purism metadata

- po/POTFILES
This is split off from https://github.com/mrvladus/Errands/pull/77
I think it's useful for the AppStream metainfo file to be translated so that people who aren't as comfortable with English can still read about the app in their app store.
I admit that there isn't much worth translating in the gschema file currently.
> Add metainfo to the list of translatable files

- errands/resources/style-dark.css
This merge request should hopefully reduce the poor colour contrast shown in Dark Mode. I've toned down the colours used in the style-dark.css so that they look less harsh, and they all either meet or exceed AAA contrast when checking with [this app.](https://flathub.org/apps/org.gnome.design.Contrast)
Compared to before:
This should close #156.
> Increase contrast for coloured tasks in dark mode

- errands/widgets/task.py
This makes the checkButton bigger, before it was easy to click on the task instead of the checkButton.
Great app, by the way!!!
> Use selection-mode for checkButton

- errands/widgets/window.py
The size of the sidebar and the overlay don't change much, but with these changes before collapsing they become a little tighter.
I personally think this would make the app feel a little more adaptive.
> Made the sidebars slightly more adaptive

- data/io.github.mrvladus.List.metainfo.xml.in.in
Appstream decided to use reverse DNS for developer IDds.
> The element should have a id property, containing a unique ID to identify the component developer / development team. It is recommended to use a reverse-DNS name, like org.gnome or io.github.ximion, or a Fediverse handle (like @user@example.org) as ID to achieve a higher chance of uniqueness.
More information: https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-developer
> Update developer ID

- errands/lib/data.py
- errands/widgets/task/task.py
- errands/widgets/trash/trash_item.py
- errands/widgets/window.py
I have tried running the dev branch of Errands and I have found few problems with trashing items. I have made fixes to these issues and made them into this PR.
These fixes include:
- Trashed tasks not being displayed on load. Refresh by trashing another task was needed to show them correctly.
- Restoring tasks was failing because of call to a non-existent method.
- Sidebar not being updated to reflect changes made by trashing task.
I have also noticed that tasks after being recovered are marked as completed. I wasn't sure if that is intended or not so I left that in.
> Fixes to trash

- errands/widgets/task_list/task_list_sidebar_row.py
- errands/widgets/trash/trash_sidebar_row.py
Small UI change to replace three dot menus with right-click menus for sidebar items as suggested in #246
One thing that I wasn't able to test is touchscreen compatibility. The way this is implemented seems like the standard way so that shouldn't be an issue.
> Replace three dot menu with right-click menu for sidebar items

- errands/lib/data.py
Avoid conflicts with other properties like `X-EVOLUTION-ALARM-UID`.
> Parse task UID properly

- errands/lib/sync/sync.py
Instead of remaining in Status Page with the message "Not Task Lists"
> Switch to Today Page after first sync

- errands/lib/data.py
Without this change if there are more than one task with a tag that is not recodred in the database then the tag is duplicated.
> Fix duplicated tags from tasks

- errands/lib/sync/sync.py
- errands/widgets/window.py
Show Syncing Page while first syncronization instead of remaining in Status Page with the message "Create new or import existing one".
> Syncing Page

- po/pt_BR.po
When carrying out translation, the conduct of removing credit in translation copyright is considered unethical and in this case I open a PULL REQUEST to insert it again. Thanks!
> Add again credit in translation removed in po/pt_BR.po

- po/errands.pot
- po/pt_BR.po
When "no task list" appears listing the lists below the title, the negation doesn't make much sense and yet I removed that negation.
Along with this change, the Brazilian Portuguese translation file was revised, the necessary changes were made, such as adding credit to Guilherme Berbet and the update was made following some lines of the file.
> A small change in the list title and review pt_BR translation

- errands/application.py
It doesn't work properly without Flatpak, because it creates the file `~/.config/autostart/.desktop` (without the app ID).
Also, use portal to remove the autostart if running under Flatpak.
> Don't use portal if not running under Flatpak

- data/meson.build
This file is not needed on runtime.
> Exclude source icon from install

- build-aux/requirements.txt
- errands/lib/sync/providers/caldav.py
Arch Linux bumped the python-caldav package to version 1.4.0. This change broke errands on this distribution. Instead of a normal caldav sync taking place, the following error message was displayed:
```
Exception in thread Thread-1 (sync):
Traceback (most recent call last):
File "/usr/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
self.run()
File "/usr/lib/python3.12/threading.py", line 1012, in run
self._target(*self._args, **self._kwargs)
File "/usr/share/errands/errands/lib/sync/sync.py", line 53, in sync
self.provider.sync()
File "/usr/share/errands/errands/lib/sync/providers/caldav.py", line 215, in sync
self.__sync_lists()
File "/usr/share/errands/errands/lib/sync/providers/caldav.py", line 235, in __sync_lists
self.__update_local_list(cal, list)
File …
```
> Fix ical import allowing caldav==1.4.0

- errands/widgets/window.py
Adds F5 as a shortcut for syncing. This brings the application inline with other GNOME applications (such as [GNOME Calendar](https://gitlab.gnome.org/GNOME/gnome-calendar/-/blob/b6c383fa907eef6c16fd7c105ae3feddf608565d/src/gui/gtk/help-overlay.ui#L39)) and popular browsers. To avoid user confusion, the previous key bind is kept.
Also, what is the reason behind the two `quit` actions?
> window: add F5 for sync
