po/LINGUAS, po/de.po
Also fixes missed PO translations in list.pot so that all strings are again translateable.
=> Add translation to deutsch.

po/it.po
Hi :-) I'd like to contribute with a few suggestions to improve the Italian translation:
- changed _menu_ to _menù_ for consistency with other strings
- _empty trash_, if I understand correctly, is a status description, not an action, i.e. "the trash is empty right now"
- _clear style_ is not the light window style but an action that resets the colour of the task
- _cancel_ is _annulla_, not _cancella_
plus other minor (self-explanatory, I hope) changes
@albanobattistella
=> Suggestions for the Italian translation

po/pt_BR.po
=> Update translation Brazilian Portuguese

TRANSLATIONS.md, data/io.github.mrvladus.List.metainfo.xml.in.in, po/tr.po
Link to the new file.
Use global link for Poedit.
=> Small data fixes and Update Turkish translation

po/ca.po
Translated everything that was missing to translate, sorry because I do not know how to apply the changes and prove that the translation has been applied correctly, I tried to save the .po file in the directory of the original folder but I can not find the path to the application, if you tell me what it is I try it right now, sorry I'm a github noob :'
=> Catalan translation

errands/resources/ui/preferences.ui, errands/utils/gsettings.py, errands/utils/sync.py, errands/widgets/preferences.py
=> Use libsecret to store passwords

po/ru.po
So i recently made the issue about internationalizing the app name (see #100), so it would be easier to find in the app menu.
This is my first(but small) contribution to such a good project, so if I did something wrong, you can easily say me about it.
=> Internatiolize the app name for Russian language

po/LINGUAS, po/zh_CN.po
Translation of Simplified Chinese
=> Add Simplified Chinese translation 

errands/widgets/window.py
=> ui: Mark a string translatable

po/es.po
The Spanish translation was incomplete, now with this it's complete. It would be good if another contributor who speaks Spanish reviews the changes. I used Poedit for this and followed the instructions mentioned in [TRANSLATIONS.md](https://github.com/mrvladus/Errands/blob/main/TRANSLATIONS.md).
=> Completed Spanish translation

po/LINGUAS, po/da_DK.po
Hi,
I just stumbled across your Application and it seems to be just what I have been looking for for a while.
I also noticed that you are currently actively maintaining it, so I figured a Danish translation might help you get more users, albeit a few.
p.s. I didn't run the tests as it seems to be necessary to do it from a sandboxed flatpak environment, or perhaps my setup was inappropriate for the task, but after installing a ton of libraries for poedit, I though I have been down the rabbit hole long enough. 
If you find that something is now up to snuff, please let me know.
=> Danish translation

po/pt_BR.po
Complete translation and correction of poorly translated texts corrected for pt_BR.
=> Translation and correction of translated texts

data/io.github.mrvladus.List.gschema.xml.in, errands/widgets/preferences.py, errands/widgets/task.py
This is the implementation of the primary action preference from issue #143.
=> Add primary action preference

po/oc.po
More translated strings into Occitan
=> Update for Occitan language

po/LINGUAS, po/el.po
There might be imperfections. I'm human after all.
If any then please let me know.
=> Added Greek Language (el)

po/LINGUAS, po/en_GB.po
Added a British English localisation for Errands. Thanks for the program, it's very useful.
=> Added British English translation

po/LINGUAS, po/ar.po
This adds Arabic translation.
*I couldn't figure out this step `Turn off compilation to .mo files on save in settings. We dont need those.`, sorry for that
=> Arabic translation

errands/widgets/task_list/task_list.py, errands/widgets/task_list/task_list.ui
#138 - Added a button to change visibility of completed tasks inside a specific list
=> #138 - Show/Hide Completed Tasks button

po/de.po
=> German Translation updated

po/ja.po
=> Updated: Japanese translation

po/fr.po
Addition of all missing French translations + minor corrections
=> Addition of all missing French translations + minor corrections

po/LINGUAS, po/sk_SK.po
Hi, I have created a Slovak translation for your app. You're doing great! Keep up the fantastic work!
=> i18n: Added Slovak translation

.gitignore, po/da_DK.po
update: Danish Translation
add: .idea to .gitignore for JetBrains IDE files
=> Update Danish Translation 46.2.6

po/fa.po
It seems fa.po file is not as updated as the app itself. courtesy of Danial Behzadi, I tried to complete his work.
=> Update Persian Translation

errands/widgets/window.py, po/ar.po, po/ca.po, po/cs.po, po/da_DK.po, po/de.po, po/el.po, po/en_GB.po, po/errands.pot, po/es.po, po/et.po, po/eu.po, po/fa.po, po/fr.po, po/hi.po, po/hr.po, po/hu.po, po/it.po, po/ja.po, po/nb.po, po/nl.po, po/oc.po, po/pl.po, po/pt_BR.po, po/ru.po, po/sk_SK.po, po/tr.po, po/uk.po, po/zh_CN.po, po/zh_TW.po
Fixes typo (syncronization -> synchronization)
Fixes #356
=> Fix typo in first synchronization

po/sk_SK.po
@terist86 Please review/comment if possible. Thx!
=> Update Slovak translation.
